CREATE TABLE Users (
  	Id INT(10) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  	UserName VARCHAR(15) NOT NULL UNIQUE DEFAULT 'anonymous'
)
ENGINE=MyISAM;

CREATE TABLE Levels (
 	Id INT(10) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
 	LevelName VARCHAR(15) NOT NULL UNIQUE DEFAULT 'test'
)
ENGINE=MyISAM;

CREATE TABLE Replay (
	Id INT(10) NOT NULL AUTO_INCREMENT PRIMARY KEY,
    User_Id INT(10),
  	Level_Id INT(10), 
  	ReplayDate DATE, 
   	ReplayTime TIME,
    ReplayData MEDIUMTEXT,
    CONSTRAINT FK_User_Id FOREIGN KEY (User_Id) REFERENCES Users (Id),
    CONSTRAINT FK_Level_Id FOREIGN KEY (Level_Id) REFERENCES Levels (Id)
)
ENGINE=MyISAM;